language: java
jdk:
  - oraclejdk8
os:
  - linux

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/wrapper/dists

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t antoineaumjaud/api-synology-chatbot:latest .;
    docker push antoineaumjaud/api-synology-chatbot;
    fi


#before_deploy:
#  - export RELEASE_PKG_FILE=$(ls build/libs/*.jar)
#  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key:
#  file: "${RELEASE_PKG_FILE}"
#  on:
#    tags: true
#    repo: antoine-aumjaud/api-syno-chatbot

